on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: build
jobs:
    py-check:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { os: windows-latest, py: "3.11" }
                    - { os: macOS-latest, py: "3.11" }
                    - { os: ubuntu-latest, py: "3.8" }
                    - { os: ubuntu-latest, py: "3.9" }
                    - { os: ubuntu-latest, py: "3.10" }
                    - { os: ubuntu-latest, py: "3.11" }

        env:
            SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
        steps:
            - name: CHECKOUT CODE
              uses: actions/checkout@v4
            - name: SETUP PYTHON
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.config.py }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --user --no-cache-dir Cython
                  pip install --user -r requirements.txt
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/
